disabled_rules:
  - line_length
  - identifier_name
  - type_name
  - trailing_comma
  - sorted_imports
  - static_over_final_class

opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicit_return
  - trailing_newline

included:
  - MidTrim
  - MidTrimTests
  - MidTrimUITests

excluded:
  - MidTrim.xcodeproj
  - DerivedData

force_unwrapping:
  severity: error

function_body_length:
  warning: 40
  error: 60

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 400
  error: 600